SCREEN_WIDTH = 80
SCREEN_HEIGHT = 50
LIMIT_FPS = 20

OBJ_PLAYER = '@'
OBJ_MOB = 'x'
OBJ_WALL = '#'
OBJ_ARMOR = '*'
OBJ_BOOTS = '^'
OBJ_GRAIL = 'G'

MESSAGE_HEALTH = "HEALTH:"
MESSAGE_ARMOUR = "ARMOUR:"
MESSAGE_SPEED = "SPEED:"

MESSAGE_HEALTH_COORDS = (2, 46)
MESSAGE_ARMOUR_COORDS = (2, 47)
MESSAGE_SPEED_COORDS = (2, 48)

STATS_HEALTH_COORDS = (10, 46)
STATS_ARMOUR_COORDS = (10, 47)
STATS_SPEED_COORDS = (10, 48)
